language: node_js
node_js:
  - "10"
  - "12"
cache: yarn

install: yarn
script:
  - echo "Not found tests"

jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: "10"
      script: yarn build
      deploy:
        provider: npm
        email: $EMAIL_ADDRESS
        api_key: $AUTH_TOKEN
        skip_cleanup: true
        on:
          tags: true
